[00;33m 	'cuda/11.3' does not supports the {CUDA_MPI}. [0m
[00;34m 	{CUDA_MPI} is only supported in cuda 11.4 version. [0m
Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]Downloading:   1%|          | 12.3k/1.04M [00:00<00:11, 87.3kB/s]Downloading:   4%|▍         | 42.0k/1.04M [00:00<00:07, 125kB/s] Downloading:   9%|▉         | 98.3k/1.04M [00:00<00:04, 201kB/s]Downloading:  20%|██        | 209k/1.04M [00:00<00:02, 344kB/s] Downloading:  42%|████▏     | 438k/1.04M [00:00<00:00, 643kB/s]Downloading:  86%|████████▌ | 897k/1.04M [00:01<00:00, 1.21MB/s]Downloading: 100%|██████████| 1.04M/1.04M [00:01<00:00, 903kB/s]
Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]Downloading:   3%|▎         | 12.3k/456k [00:00<00:06, 64.2kB/s]Downloading:   7%|▋         | 32.8k/456k [00:00<00:04, 89.3kB/s]Downloading:  19%|█▉        | 86.0k/456k [00:00<00:02, 175kB/s] Downloading:  47%|████▋     | 213k/456k [00:00<00:00, 368kB/s] Downloading:  93%|█████████▎| 426k/456k [00:00<00:00, 636kB/s]Downloading: 100%|██████████| 456k/456k [00:00<00:00, 476kB/s]
Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]Downloading: 100%|██████████| 665/665 [00:00<00:00, 1.22MB/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "main_gpt2_with_health_checker.py", line 527, in <module>
    trainer = Trainer(world_size, rank, bucket_size, count, adaptive_shard_ratio, health_check_scheduler_thread, health_check_main_proc, health_check_thread_ready, trial_info, thread) 
  File "main_gpt2_with_health_checker.py", line 202, in __init__
    train_sampler = DistributedSampler(dataset=self.train_dataset, shuffle=False)
AttributeError: 'Trainer' object has no attribute 'train_dataset'
Traceback (most recent call last):
  File "main_gpt2_with_health_checker.py", line 527, in <module>
    trainer = Trainer(world_size, rank, bucket_size, count, adaptive_shard_ratio, health_check_scheduler_thread, health_check_main_proc, health_check_thread_ready, trial_info, thread) 
  File "main_gpt2_with_health_checker.py", line 202, in __init__
    train_sampler = DistributedSampler(dataset=self.train_dataset, shuffle=False)
AttributeError: 'Trainer' object has no attribute 'train_dataset'
Traceback (most recent call last):
  File "main_gpt2_with_health_checker.py", line 527, in <module>
    trainer = Trainer(world_size, rank, bucket_size, count, adaptive_shard_ratio, health_check_scheduler_thread, health_check_main_proc, health_check_thread_ready, trial_info, thread) 
  File "main_gpt2_with_health_checker.py", line 202, in __init__
    train_sampler = DistributedSampler(dataset=self.train_dataset, shuffle=False)
AttributeError: 'Trainer' object has no attribute 'train_dataset'
Traceback (most recent call last):
  File "main_gpt2_with_health_checker.py", line 527, in <module>
    trainer = Trainer(world_size, rank, bucket_size, count, adaptive_shard_ratio, health_check_scheduler_thread, health_check_main_proc, health_check_thread_ready, trial_info, thread) 
  File "main_gpt2_with_health_checker.py", line 202, in __init__
    train_sampler = DistributedSampler(dataset=self.train_dataset, shuffle=False)
AttributeError: 'Trainer' object has no attribute 'train_dataset'
srun: error: gpu07: tasks 0-1,3: Exited with exit code 1
srun: error: gpu07: task 2: Exited with exit code 1
